language: php

php:
  - 7.3

before_script:
  - cp .docker/php/.env.travis .env.testing
  - cp .docker/php/.env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
