language: php

php:
  - 7.3

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .docker/php/.env.travis .env.testing
  - sudo mysql -e 'create database codeflix_videos_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
