language: php
sudo: required

php:
  - 7.3

addons:
  mariadb: '10.0'

before_install:
  - mysql -e 'create database testing;'

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .docker/php/.env.travis .env.testing
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
